apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubetriage.fullname" . }}-backend
  labels:
    {{- include "kubetriage.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubetriage.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubetriage.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubetriage.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          env:
            - name: PORT
              value: "{{ .Values.backend.env.PORT }}"
            - name: MOCK_OIDC
              value: "{{ .Values.backend.env.MOCK_OIDC }}"
            - name: FRONTEND_URL
              value: "{{ .Values.backend.env.FRONTEND_URL }}"
            {{- if .Values.backend.env.REDIS_ADDR }}
            - name: REDIS_ADDR
              value: "{{ .Values.backend.env.REDIS_ADDR }}"
            {{- else }}
            - name: REDIS_ADDR
              value: "{{ .Release.Name }}-redis-master:6379"
            {{- end }}
            {{- if .Values.backend.env.GEMINI_API_KEY }}
            - name: GEMINI_API_KEY
              value: "{{ .Values.backend.env.GEMINI_API_KEY }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
